# Generated by Django 4.1.5 on 2023-01-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_text_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
