# Generated by Django 4.1.5 on 2023-01-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecategory',
            name='slug',
        ),
    ]
