# Generated by Django 4.1.5 on 2023-01-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesectioncategory',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pageSectionCategory', to='frontend.pagesection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagesectioncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageCategory', to='frontend.pagecategory'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionImage', to='frontend.pagesection'),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionText', to='frontend.pagesection'),
        ),
    ]
