# Generated by Django 4.1.5 on 2023-01-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_carsoul_rename_category_sectionimage_pagesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsoul',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web/page/slider/'),
        ),
    ]
